// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('This app supports only Android and iOS.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAhRwbOB9RZMdLxfFnREL7IlY8kXs0eI',
    appId: '1:338961196167:web:4c3c1c8219ea0c45190422',
    messagingSenderId: '338961196167',
    projectId: 'splitzon',
    authDomain: 'splitzon.firebaseapp.com',
    storageBucket: 'splitzon.firebasestorage.app',
    measurementId: 'G-R9HV34ER43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNVGdleXFXXagYbIUPgMktvD75A-Ra5Ws',
    appId: '1:338961196167:android:cec51d815bdaba38190422',
    messagingSenderId: '338961196167',
    projectId: 'splitzon',
    storageBucket: 'splitzon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHGGZpBlsqE5NlPSyLJmItxjBk72CiwWg',
    appId: '1:338961196167:ios:96f084c6271d74ff190422',
    messagingSenderId: '338961196167',
    projectId: 'splitzon',
    storageBucket: 'splitzon.firebasestorage.app',
    iosBundleId: 'com.example.splitzon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHGGZpBlsqE5NlPSyLJmItxjBk72CiwWg',
    appId: '1:338961196167:ios:96f084c6271d74ff190422',
    messagingSenderId: '338961196167',
    projectId: 'splitzon',
    storageBucket: 'splitzon.firebasestorage.app',
    iosBundleId: 'com.example.splitzon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAhRwbOB9RZMdLxfFnREL7IlY8kXs0eI',
    appId: '1:338961196167:web:f3e459a994c02c00190422',
    messagingSenderId: '338961196167',
    projectId: 'splitzon',
    authDomain: 'splitzon.firebaseapp.com',
    storageBucket: 'splitzon.firebasestorage.app',
    measurementId: 'G-7CS9BCMLMW',
  );
}
